version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "storeDayZ"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - ./store_DayZ/src/main/resources/scripts:/docker-entrypoint-initdb.d
    ports:
      - "25432:5432"
    networks:
      - postgres
  storedayz-backend:
    build: backend_module
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    networks:
      - postgres
  frontend-container:
    build: frontend_module
    ports:
      - "3000:3000"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge